name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup dotnet 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Build app
        run: dotnet build --no-restore

      